# Generated by Django 3.0.3 on 2020-02-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default_slug', max_length=200),
            preserve_default=False,
        ),
    ]
