# Generated by Django 3.0.3 on 2020-04-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ref_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forum.Post'),
        ),
    ]
