# Generated by Django 3.0.3 on 2020-04-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_ref_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ref_post',
            new_name='refpost',
        ),
    ]
